### ISSUE TITLE
Can't export UL or OL

### ISSUE THREAD

**Issue by buecherlstefan** [onizet/html2openxml#151]
**Describe the bug**
SystemArgument Exception - When export a simple ul

**Expected behavior**
No Exception - The UL should be converted

**Repro**
Version 3.0.0-beta
`<ul><li><span></span>ssssssss</li></ul>`

**Exception**
Did not expect System.Exception, but found System.ArgumentException: An item with the same key has already been added. Key: 18
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at HtmlToOpenXml.Expressions.NumberingExpressionBase.InitNumberingIds(ParsingContext context) in /Users/olivier/Projects/html2openxml/src/Html2OpenXml/Expressions/NumberingExpressionBase.cs:line 210
   at HtmlToOpenXml.Expressions.NumberingExpressionBase.GetOrCreateListTemplate(ParsingContext context, String listName) in /Users/olivier/Projects/html2openxml/src/Html2OpenXml/Expressions/NumberingExpressionBase.cs:line 42
   at HtmlToOpenXml.Expressions.ListExpression.Interpret(ParsingContext context)+MoveNext() in /Users/olivier/Projects/html2openxml/src/Html2OpenXml/Expressions/ListExpression.cs:line 60
   at HtmlToOpenXml.Expressions.BlockElementExpression.ComposeChildren(ParsingContext context, IEnumerable`1 childNodes, ParagraphProperties paragraphProperties, Action`1 preAction, Action`1 postAction) in /Users/olivier/Projects/html2openxml/src/Html2OpenXml/Expressions/BlockElementExpression.cs:line 228
   at HtmlToOpenXml.Expressions.BlockElementExpression.Interpret(ParsingContext context, IEnumerable`1 childNodes) in /Users/olivier/Projects/html2openxml/src/Html2OpenXml/Expressions/BlockElementExpression.cs:line 50
   at HtmlToOpenXml.Expressions.PhrasingElementExpression.Interpret(ParsingContext context) in /Users/olivier/Projects/html2openxml/src/Html2OpenXml/Expressions/PhrasingElementExpression.cs:line 40
   at HtmlToOpenXml.Expressions.BlockElementExpression.Interpret(ParsingContext context) in /Users/olivier/Projects/html2openxml/src/Html2OpenXml/Expressions/BlockElementExpression.cs:line 35
   at HtmlToOpenXml.Expressions.BodyExpression.Interpret(ParsingContext context) in /Users/olivier/Projects/html2openxml/src/Html2OpenXml/Expressions/BodyExpression.cs:line 31
   at HtmlToOpenXml.HtmlConverter.Parse(String html, ParallelOptions parallelOptions) in /Users/olivier/Projects/html2openxml/src/Html2OpenXml/HtmlConverter.cs:line 106
   at HtmlToOpenXml.HtmlConverter.Parse(String html) in /Users/olivier/Projects/html2openxml/src/Html2OpenXml/HtmlConverter.cs:line 66

**Comment by onizet** [comment]
Hello, are you using an existing template?

**Comment by buecherlstefan** [comment]
Yes i am using this template: https://www.transfernow.net/dl/20240708FbEhwm6n

**Comment by buecherlstefan** [comment]
Many thanks for this quick support!!! 👍
