### ISSUE TITLE
.NET CORE compatibility issue

### ISSUE THREAD

**Issue by tgranie** [onizet/html2openxml#184]
Hello,

I'm trying using  Html2OpenXml in my ASP.NET application in .NET 7.0 in a get this issue :

System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Penman.Html2OpenXml.HtmlConverter.ProcessHtmlChunks(HtmlEnumerator en, String endTag)
   at Penman.Html2OpenXml.HtmlConverter.Parse(String html)
   at Penman.Html2OpenXml.HtmlConverter.ParseHtml(String html)

To test I migrate to .NET 8.0, same issue.

Thanks for your help and thanks for this usefull lib !

**Comment by onizet** [comment]
Hello, I just did a test with .net 7.0 and didn't get any issue.

Did you reference this package? `<PackageReference Include="HtmlToOpenXml.dll" Version="3.2.2" />
` (please note the ending `.dll`, because the other package exists also but is very old)

**Comment by markayby** [comment]
I've had the same issue on .net 8 and package v2.2.1. Fixed by upgrade to 3.2.2 as suggested

**Comment by tgranie** [comment]
Sorry and Thanks @markayby @onizet I was using the fork Penman.Html2OpenXml
